version: '2'

networks:
  app-tier:
    driver: bridge

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.15.0'
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"  
    ports:
      - 9200:9200
    networks:
      - app-tier      
  
  kibana:
    image: 'bitnami/kibana:7.14.2'
    container_name: kibana
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch       
    ports:
      - 5601:5601      
    networks:
      - app-tier

  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    container_name: zookeeper
    ports:
      - 2181:2181       
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier

  kafka:
    image: 'bitnami/kafka:3.0.0'
    container_name: kafka
    ports:
      - 9092:9092
    volumes:
      - $PWD/kafka:/var/lib/kafka      
    environment:
      - 'KAFKA_BROKER_ID=1'
      - 'ALLOW_PLAINTEXT_LISTENER=yes'  
      - 'KAFKA_CFG_LISTENERS=PLAINTEXT://:9092'
      - 'KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092'
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181'
    depends_on:
      - zookeeper      
    networks:
      - app-tier      

  mysql:
    image: 'bitnami/mysql:8.0'
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - $PWD/mysql:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=test'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=test'
      - 'MYSQL_ROOT_PASSWORD=123'
    networks:
      - app-tier

  logstash:  
    image: logstash:7.14.2
    container_name: logstash
    #command: /usr/share/logstash/bin/logstash --path.data sensor39 -f /var/lib/logstash/mysql-input.conf
    volumes:
      - $PWD/logstash:/var/lib/logstash      
    depends_on:
      - mysql
      - elasticsearch
      - kafka      
    networks:
      - app-tier      


volumes:
  mysql:
    driver: local
  logstash:
    driver: local      
  kafka:
    driver: local     
